### ISSUE TITLE
Jenkins Credentials filled with 'sonar-gerrti:{GUID}' secrets

### ISSUE THREAD

**Issue by Levistator** [jenkinsci/sonar-gerrit-plugin#112]
During an investigation I found that my `jenkins > global` credentials  store was filled with a TON of `sonar-gerrit:{GUID}` secrets.
![sonar-gerrit_credentials](https://user-images.githubusercontent.com/3744568/149596483-f57f6f42-cdf8-4ca3-95c5-53ccc88e1dab.jpg)
There are more than my webpage can load. 

I'm simply trying to investigate where these came from and whether I can delete them all. 

Thank you for your help

**Comment by reda-alaoui** [comment]
Those credentials were certainly created by https://github.com/jenkinsci/sonar-gerrit-plugin/pull/97. 

Before https://github.com/jenkinsci/sonar-gerrit-plugin/pull/97 , you could override Gerrit credentials in each job configuration by storing directly a username/password.
https://github.com/jenkinsci/sonar-gerrit-plugin/pull/97 moved all of those credentials into global credentials.

**Comment by Levistator** [comment]
Thank you very much for the information! I'll make sure that all jobs that
need to be updated are!

It turns out there were 146,000 of those entries that I had to clean up
😳😳.

This can be closed if it hasn't been already.

Thank you very much!

**Comment by reda-alaoui** [comment]
You are supposed to have one credential entry per overriden Gerrit credentials.
I doubt you have 146,000 jobs that overrides the Gerrit credentials.
Did you recognize the username stored in each entry? It may be a bug.

**Comment by Levistator** [comment]
Only a very very small subset (I think I saw 3?) of the credentials had
usernames actually. Most were only passwords.

**Comment by RestlessHeart** [comment]
Hi @reda-alaoui ,
I also get this problem with latest version: 370.vf2cf40f43d41
![image](https://user-images.githubusercontent.com/5730495/156327006-e4668360-b032-4020-8ab2-62f1097a4e45.png)
It seems there is problem in   [public Optional<String> migrate(String username, Secret password)](https://github.com/jenkinsci/sonar-gerrit-plugin/blob/43ab52ab23a5bc61cba2d652430815a7a73105fd/src/main/java/org/jenkinsci/plugins/sonargerrit/gerrit/GerritHttpCredentials.java#L39)
It could not create a credential which could match what we provide by username/password.
As you can see, there is no username in autogenerated credentials.
![image](https://user-images.githubusercontent.com/5730495/156328941-28559e4a-145b-4250-98c6-9d468c6270be.png)
So it try to create new credentials again and again.

Here is the snippet how we use this plugin:
 `authConfig: [
                        username: "${FUNCTIONAL_CRED_USR}",
                        password: "${FUNCTIONAL_CRED_PSW}"
                ]`
FUNCTIONAL_CRED_USR and FUNCTIONAL_CRED_PSW are username/password provided by Credentials Binding plugin.

Could you help to check this issue?

**Comment by RestlessHeart** [comment]
Thanks for your fix. It works now.
