### ISSUE TITLE
Support Sonarqube community edition default image 

### ISSUE THREAD

**Issue by joel-schaal** [jenkinsci/sonar-gerrit-plugin#119]
### What feature do you want to see added?

While I appreciate the work done in the context of #46, adding the requirement of a plugin can sometimes be cumbersome (ex: when this ticket was entered, the [mc1arke docker image](https://hub.docker.com/r/mc1arke/sonarqube-with-community-branch-plugin/tags) was 2 versions behind upstream) or unwanted (we would like to reduce the number of moving parts to secure/maintain).

I'd rather like to use the default APIs of Sonarqube Community to start an analysis and post comments on the Gerrit server. 
From what I understand, the [official docs](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-jenkins/) use a dedicated "Quality Gate" stage in order to achieve that.
Can `sonarToGerrit` evolve to use a similar mechanism ?

**Comment by reda-alaoui** [comment]
Hello @joel-schaal ,

I am not sure to understand what you want.
We only use Docker images for test purposes.

> adding the requirement of a plugin can sometimes be cumbersome 

What plugin are you talking about?

**Comment by joel-schaal** [comment]
Hello, re-reading my post I realize some information was indeed missing.

What I meant is that we cannot use the [default image of sonarqube](https://hub.docker.com/_/sonarqube) but rather use a custom one, where the [sonarqube-community-branch-plugin](https://github.com/mc1arke/sonarqube-community-branch-plugin) has been installed. 

In my use case, the Sonarqube production server is (or rather will be) a Docker image.

**Comment by reda-alaoui** [comment]
Please note that the plugin exposes same pull request decoration api as the SonarQube developper edition.

**Comment by reda-alaoui** [comment]
Closing until further information is provided.
